# Generated by Django 3.2.6 on 2024-07-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openstacks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rulesmodel',
            name='remote_ip_prefix',
            field=models.GenericIPAddressField(blank=True, default=None, null=True, verbose_name='IP段'),
        ),
    ]
