# Generated by Django 3.2.6 on 2024-07-04 14:11

import apps.openstacks.models.records
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openstacks', '0002_alter_rulesmodel_remote_ip_prefix'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recordsmodel',
            options={'ordering': ['-create_time'], 'verbose_name': '纪录'},
        ),
        migrations.AlterModelManagers(
            name='recordsmodel',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='recordsmodel',
            name='project',
        ),
        migrations.RemoveField(
            model_name='recordsmodel',
            name='user',
        ),
        migrations.AddField(
            model_name='recordsmodel',
            name='resource_id',
            field=models.CharField(db_index=True, default='', max_length=255, verbose_name='资源ID'),
        ),
        migrations.AlterField(
            model_name='recordsmodel',
            name='action_type',
            field=models.CharField(choices=[('CREATE', '创建'), ('UPDATE', '更新'), ('DELETE', '删除')], max_length=20, verbose_name='操作'),
        ),
        migrations.AlterField(
            model_name='recordsmodel',
            name='details',
            field=models.JSONField(default=apps.openstacks.models.records.RecordsModel._default, verbose_name='详情'),
        ),
        migrations.AlterField(
            model_name='recordsmodel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='recordsmodel',
            name='resource',
            field=models.CharField(db_index=True, max_length=255, verbose_name='资源名称'),
        ),
        migrations.AlterField(
            model_name='recordsmodel',
            name='status',
            field=models.CharField(default='SUCCESS', max_length=20, verbose_name='状态'),
        ),
    ]
