# Generated by Django 3.2.6 on 2024-07-11 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openstacks', '0003_auto_20240704_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressthrough',
            name='port',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='openstacks.portsmodel'),
        ),
        migrations.AlterField(
            model_name='addressthrough',
            name='subnet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='openstacks.subnetsmodel'),
        ),
        migrations.AlterField(
            model_name='rulesmodel',
            name='port_range_max',
            field=models.PositiveIntegerField(default=None, null=True, verbose_name='结束端口'),
        ),
        migrations.AlterField(
            model_name='rulesmodel',
            name='port_range_min',
            field=models.PositiveIntegerField(default=None, null=True, verbose_name='起始端口'),
        ),
        migrations.AlterField(
            model_name='rulesmodel',
            name='security_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='openstacks.securitygroupsmodel', verbose_name='所属安全组'),
        ),
        migrations.AlterField(
            model_name='volumesattachments',
            name='server',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attach', to='openstacks.serversmodel'),
        ),
        migrations.AlterField(
            model_name='volumesattachments',
            name='volume',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attach', to='openstacks.volumesmodel'),
        ),
    ]
